title: 🇺🇦🇦🇹 Support for Ukrainians in Austria
lang: "ua, de, en"
author:
  name: 'Github User'
  email: 'github@example.com'
description: >- # this means to ignore newlines until "baseurl:"
  This page collects important and useful information for everyone who comes to Austria from Ukraine and for those who help them.

excerpts:
  # Displays or hides post excerpts from home layout post listing.
  show: true
  # Cuts off excerpts with an ellipsis (...) after 32 words (approx. 2 lines).
  # You can also leave this false, and manually control excerpt length:
  # https://jekyllrb.com/docs/posts/#post-excerpts
  auto_truncate: true

# Theme configuration
bootstrap:
  # Theme date format
  # refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
  date_format: "%b %-d, %Y"

  # If you want to link only specific pages in your header, uncomment
  # this and add the path to the page *files* in order as they should show up
  header_pages:

plugins:
  - jekyll-seo-tag
